import Hasil from './Hasil'
import ListCategories from './ListCategories'
import NavbarComponent from './NavbarComponent'
import Menus from './Menus'
import TableList from '../pages/Table/Component/TableList'
import DetailMeja from '../pages/Table/Component/DetailMeja'
import DashboardSide from '../pages/Dashboard/Component/DashboardSide'
import WaitingList from '../pages/Dashboard/Component/WaitingList'
import ListMenuCategory from '../pages/Resto/Component/ListMenuCategory'
import ListMenu from '../pages/Resto/Component/ListMenu'
import Order from '../pages/Resto/Component/Order'
import LineChart from '../pages/Chart/Component/LineChart'
import StackedChart from '../pages/Chart/Component/StackedChart'

export { Hasil, ListCategories, NavbarComponent, Menus, TableList, WaitingList, DetailMeja, DashboardSide, ListMenuCategory, ListMenu, Order, LineChart, StackedChart}